// Core types for the ranking game API

// Vote record stored in blob storage
export interface VoteRecord {
  winnerId: string;
  loserId: string;
  timestamp: number;
}

// Global rating snapshot generated by cron job
export interface GlobalRatingSnapshot {
  updatedAt: number;
  ratings: Record<string, { 
    elo: number; 
    wins: number; 
    losses: number; 
    matches: number;
  }>;
}

// Game state returned by /api/game/state
export interface GameState {
  sessionId: string;
  comparisons: number;
  progressPercent: number;
  seenPairs: string[];
}

// Vote request body for /api/game/vote
export interface VoteRequest {
  sessionId: string;
  pairId?: string; // Optional, not used in backend
  aId: string;
  bId: string;
  outcome: "A" | "B";
}

// Ranking entry returned by /api/ranking/* endpoints
export interface RankingEntry {
  rank: number;
  candidateId: string;
  name: string;
  ideologia?: string;
  rating: number;
  score: number;
  wins?: number;
  losses?: number;
  games: number;
  winRate: number;
  rd: number;
}

// Frontend-only types (not used by API)
export interface Pair {
  pairId: string;
  a: {
    id: string;
    nombre: string;
    ideologia?: string;
    fullBody?: string;
    headshot?: string;
  };
  b: {
    id: string;
    nombre: string;
    ideologia?: string;
    fullBody?: string;
    headshot?: string;
  };
  hint?: {
    rationale: "random";
  };
}

// Legacy type alias for compatibility
export type GlobalRankingEntry = RankingEntry;
